stages:
  # Load GND vocabulary
  load-vocab:
    cmd: annif load-vocab --force gnd shared-task-datasets/GND/GND-Subjects-all_dnb-skos-with-en-labels.ttl
    deps:
    - shared-task-datasets/GND/GND-Subjects-all_dnb-skos-with-en-labels.ttl
    outs:
    - data/vocabs/gnd
  # Train MLLM projects
  train-mllm:
    foreach:
      - en
      - de
    do:
      cmd: annif train gnd-mllm-${item} shared-task-datasets/TIBKAT/all-subjects/data/train/*/${item}.tsv
      deps:
      - shared-task-datasets/TIBKAT/all-subjects/data/train/
      - data/vocabs/gnd
      params:
      - projects.toml:
        - gnd-mllm-${item}
      outs:
      - data/projects/gnd-mllm-${item}
  # Train Omikuji Bonsai projects
  train-omikuji-bonsai:
    foreach:
      - en
      - de
    do:
      cmd: annif train gnd-bonsai-${item} shared-task-datasets/TIBKAT/all-subjects/data/train/*/${item}.tsv
      deps:
      - shared-task-datasets/TIBKAT/all-subjects/data/train/
      - data/vocabs/gnd
      params:
      - projects.toml:
        - gnd-bonsai-${item}
      outs:
      - data/projects/gnd-bonsai-${item}
  # Evaluate projects
  eval:
    matrix:
      backend: [mllm, bonsai]
      lang: [en, de]
    cmd:
    - annif eval gnd-${item.backend}-${item.lang} -j 32 -m F1@5 -m NDCG --metrics-file reports/${item.backend}-${item.lang}.json shared-task-datasets/TIBKAT/all-subjects/data/dev/*/${item.lang}.tsv
    deps:
    - shared-task-datasets/TIBKAT/all-subjects/data/dev/Article/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/all-subjects/data/dev/Book/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/all-subjects/data/dev/Conference/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/all-subjects/data/dev/Report/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/all-subjects/data/dev/Thesis/${item.lang}.tsv
    - data/projects/gnd-${item.backend}-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.backend}-${item.lang}
    metrics:
    - reports/${item.backend}-${item.lang}.json:
        cache: false
