stages:
  # Train MLLM projects
  train-mllm:
    matrix:
      vocab: [all, tib-core]
      lang: [en, de]
    cmd: annif train -j 32 gnd-${item.vocab}-mllm-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    - data/vocabs/gnd-${item.vocab}
    params:
    - projects.toml:
      - gnd-${item.vocab}-mllm-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-mllm-${item.lang}
  # Train Omikuji Bonsai projects
  train-bonsai:
    matrix:
      vocab: [all, tib-core]
      lang: [en, de]
    cmd: annif train -j 32 gnd-${item.vocab}-bonsai-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-*.tsv.gz shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-1.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-2.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-3.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    - data/vocabs/gnd-${item.vocab}
    params:
    - projects.toml:
      - gnd-${item.vocab}-bonsai-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-bonsai-${item.lang}
  # Train xtransformer projects
  train-xtransformer:
    matrix:
      vocab: [all, tib-core]
      lang: [en, de]
    cmd:
    - annif train -j 1 gnd-${item.vocab}-xtransformer-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-1.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-2.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/synth-${item.lang}-3.tsv.gz
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/${item.lang}.tsv.gz
    - data/vocabs/gnd-${item.vocab}
    params:
    - projects.toml:
      - gnd-${item.vocab}-xtransformer-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-xtransformer-${item.lang}
  # Train NN ensemble projects
  train-nn_ensemble:
    matrix:
      vocab: [all, tib-core]
      lang: [en, de]
    cmd: annif train -j 32 gnd-${item.vocab}-nn_ensemble-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    - data/vocabs/gnd-${item.vocab}
    - data/projects/gnd-${item.vocab}-bonsai-${item.lang}
    - data/projects/gnd-${item.vocab}-mllm-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.vocab}-nn_ensemble-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-nn_ensemble-${item.lang}
  # Dummy "train" ensemble, i.e. create the datadir needed as dependency in eval
  dummy-train-bm-ensemble:
    matrix:
      vocab: [all, tib-core]
      sources: [bm]
      lang: [en, de]
    cmd:
    - mkdir -p data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
    - date -u > data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}/timestamp
    deps:
    - data/vocabs/gnd-${item.vocab}
    - data/projects/gnd-${item.vocab}-bonsai-${item.lang}
    - data/projects/gnd-${item.vocab}-mllm-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
  dummy-train-bmx-ensemble:
    matrix:
      vocab: [all, tib-core]
      sources: [bmx]
      lang: [en, de]
    cmd:
    - mkdir -p data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
    - date -u > data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}/timestamp
    deps:
    - data/vocabs/gnd-${item.vocab}
    - data/projects/gnd-${item.vocab}-bonsai-${item.lang}
    - data/projects/gnd-${item.vocab}-mllm-${item.lang}
    - data/projects/gnd-${item.vocab}-xtransformer-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
  # Evaluate projects
  eval:
    matrix:
      vocab: [all, tib-core]
      backend: [mllm, bonsai, xtransformer, bm-ensemble, bmx-ensemble, nn_ensemble]
      lang: [en, de]
    cmd:
    - annif eval gnd-${item.vocab}-${item.backend}-${item.lang} -j $ANNIF_EVAL_JOBS -m F1@5 -m NDCG --metrics-file reports/${item.vocab}-${item.backend}-${item.lang}.json shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    - data/projects/gnd-${item.vocab}-${item.backend}-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.backend}-${item.lang}
    metrics:
    - reports/${item.vocab}-${item.backend}-${item.lang}.json:
        cache: false
  # Optimize ensemble weights against the dev sets
  hyperopt-ensemble:
    matrix:
      vocab: [all, tib-core]
      sources: [bm, bmx]
      lang: [en, de]
    cmd:
    - annif hyperopt -j 1 --trials 200 gnd-${item.vocab}-${item.sources}-ensemble-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/${item.lang}.tsv.gz
    - data/projects/gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.sources}-ensemble-${item.lang}
