stages:
  # Train projects
  train:
    matrix:
      vocab: [all, tib-core]
      backend: [mllm, bonsai]
      lang: [en, de]
    cmd: annif train gnd-${item.vocab}-${item.backend}-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/*/${item.lang}.tsv
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/
    - data/vocabs/gnd-${item.vocab}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.backend}-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-${item.backend}-${item.lang}
  # Dummy "train" ensemble, i.e. create the datadir needed as dependency in eval
  dummy-train-ensemble:
    matrix:
      vocab: [all, tib-core]
      lang: [en, de]
    cmd: mkdir -p data/projects/gnd-${item.vocab}-ensemble-${item.lang}
    deps:
    - data/vocabs/gnd-${item.vocab}
    - data/projects/gnd-${item.vocab}-bonsai-${item.lang}
    - data/projects/gnd-${item.vocab}-mllm-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-ensemble-${item.lang}
  # Evaluate projects
  eval:
    matrix:
      vocab: [all, tib-core]
      backend: [mllm, bonsai, ensemble]
      lang: [en, de]
    cmd:
    - annif eval gnd-${item.vocab}-${item.backend}-${item.lang} -j 32 -m F1@5 -m NDCG --metrics-file reports/${item.vocab}-${item.backend}-${item.lang}.json shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/*/${item.lang}.tsv
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Article/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Book/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Conference/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Report/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Thesis/${item.lang}.tsv
    - data/projects/gnd-${item.vocab}-${item.backend}-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.backend}-${item.lang}
    metrics:
    - reports/${item.vocab}-${item.backend}-${item.lang}.json:
        cache: false
