stages:
  # Load vocabularies
  load-vocab:
    foreach:
      - all
      - tib-core
    do:
      cmd: annif load-vocab --force gnd-${item} shared-task-datasets/GND/GND-Subjects-${item}_dnb-skos-with-en-labels.ttl
      deps:
      - shared-task-datasets/GND/GND-Subjects-${item}_dnb-skos-with-en-labels.ttl
      outs:
      - data/vocabs/gnd-${item}
  # Train projects
  train:
    matrix:
      vocab: [all, tib-core]
      backend: [mllm, bonsai]
      lang: [en, de]
    cmd: annif train gnd-${item.vocab}-${item.backend}-${item.lang} shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/*/${item.lang}.tsv
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/train/
    - data/vocabs/gnd-${item.vocab}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.backend}-${item.lang}
    outs:
    - data/projects/gnd-${item.vocab}-${item.backend}-${item.lang}
  # Evaluate projects
  eval:
    matrix:
      vocab: [all, tib-core]
      backend: [mllm, bonsai]
      lang: [en, de]
    cmd:
    - annif eval gnd-${item.vocab}-${item.backend}-${item.lang} -j 32 -m F1@5 -m NDCG --metrics-file reports/${item.vocab}-${item.backend}-${item.lang}.json shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/*/${item.lang}.tsv
    deps:
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Article/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Book/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Conference/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Report/${item.lang}.tsv
    - shared-task-datasets/TIBKAT/${item.vocab}-subjects/data/dev/Thesis/${item.lang}.tsv
    - data/projects/gnd-${item.vocab}-${item.backend}-${item.lang}
    params:
    - projects.toml:
      - gnd-${item.vocab}-${item.backend}-${item.lang}
    metrics:
    - reports/${item.vocab}-${item.backend}-${item.lang}.json:
        cache: false
