[gnd-all-mllm-en]
name = "GND-all MLLM English"
language = "en"
backend = "mllm"
analyzer = "simplemma(en)"
vocab = "gnd-all"

[gnd-all-mllm-de]
name = "GND-all MLLM German"
language = "de"
backend = "mllm"
analyzer = "snowball(german)"
vocab = "gnd-all"

[gnd-all-bonsai-en]
name = "GND-all Omikuji Bonsai English"
language = "en"
backend = "omikuji"
analyzer = "snowball(english)"
vocab = "gnd-all"
cluster_balanced = "False"
cluster_k = "100"
max_depth = "3"
min_df = "5"
ngram = "2"

[gnd-all-bonsai-de]
name = "GND-all Omikuji Bonsai German"
language = "de"
backend = "omikuji"
analyzer = "snowball(german)"
vocab = "gnd-all"
cluster_balanced = "False"
cluster_k = "100"
max_depth = "3"
min_df = "2"
ngram = "2"

[gnd-all-bm-ensemble-en]
name = "GND-all BM ensemble English"
language = "en"
backend = "ensemble"
sources = "gnd-all-mllm-en:0.1623,gnd-all-bonsai-en:0.8377"
vocab = "gnd-all"

[gnd-all-bm-ensemble-de]
name = "GND-all BM ensemble German"
language = "de"
backend = "ensemble"
sources = "gnd-all-mllm-de:0.1930,gnd-all-bonsai-de:0.8070"
vocab = "gnd-all"

[gnd-all-bmx-ensemble-en]
name = "GND-all BMX ensemble English"
language = "en"
backend = "ensemble"
sources = "gnd-all-mllm-en:0.1417,gnd-all-bonsai-en:0.5387,gnd-all-xtransformer-en:0.3196"
vocab = "gnd-all"

[gnd-all-bmx-ensemble-de]
name = "GND-all BMX ensemble German"
language = "de"
backend = "ensemble"
sources = "gnd-all-mllm-de:0.1964,gnd-all-bonsai-de:0.4713,gnd-all-xtransformer-de:0.3323"
vocab = "gnd-all"

[gnd-all-nn_ensemble-en]
name = "GND-all NN ensemble English"
language = "en"
backend = "nn_ensemble"
sources = "gnd-all-mllm-en:0.1623,gnd-all-bonsai-en:0.8377"
vocab = "gnd-all"
nodes = 100
dropout_rate = 0.2
epochs = 10

[gnd-all-nn_ensemble-de]
name = "GND-all NN ensemble German"
language = "de"
backend = "nn_ensemble"
sources = "gnd-all-mllm-de:0.1930,gnd-all-bonsai-de:0.8070"
vocab = "gnd-all"
nodes = 100
dropout_rate = 0.2
epochs = 10

[gnd-all-xtransformer-en]
name="GND-all XTransformer English"
language="en"
backend="xtransformer"
analyzer="snowball(english)"
vocab="gnd-all"
batch_size=16
truncate_length=256
learning_rate=0.0001
num_train_epochs=3
max_leaf_size=1600
nr_splits=256
threshold=0.015
Cn=0.52
Cp=5.33
bootstrap_model="weighted-linear"
loss_function="weighted-squared-hinge"
max_active_matching_labels=500
negative_sampling="tfn+man"
warmup_steps=200
ensemble_method="concat-only"
post_processor="l3-hinge"
cost_sensitive_ranker=true
rel_mode="induce"
rel_norm="l1"
neg_mining_chain="tfn"
model_shortcut="FacebookAI/xlm-roberta-base"

[gnd-all-xtransformer-de]
name="GND-all XTransformer German"
language="de"
backend="xtransformer"
analyzer="snowball(german)"
vocab="gnd-all"
batch_size=16
truncate_length=256
learning_rate=0.0001
num_train_epochs=3
max_leaf_size=1600
nr_splits=256
threshold=0.015
Cn=0.52
Cp=5.33
bootstrap_model="weighted-linear"
loss_function="weighted-squared-hinge"
max_active_matching_labels=500
negative_sampling="tfn+man"
warmup_steps=200
ensemble_method="concat-only"
post_processor="l3-hinge"
cost_sensitive_ranker=true
rel_mode="induce"
rel_norm="l1"
neg_mining_chain="tfn"
model_shortcut="FacebookAI/xlm-roberta-base"

[gnd-tib-core-mllm-en]
name = "GND-tib-core MLLM English"
language = "en"
backend = "mllm"
analyzer = "snowball(english)"
vocab = "gnd-tib-core"

[gnd-tib-core-mllm-de]
name = "GND-tib-core MLLM German"
language = "de"
backend = "mllm"
analyzer = "snowball(german)"
vocab = "gnd-tib-core"

[gnd-tib-core-bonsai-en]
name = "GND-tib-core Omikuji Bonsai English"
language = "en"
backend = "omikuji"
analyzer = "snowball(english)"
vocab = "gnd-tib-core"
cluster_balanced = "False"
cluster_k = "100"
max_depth = "3"
min_df = "2"
ngram = "2"

[gnd-tib-core-bonsai-de]
name = "GND-tib-core Omikuji Bonsai German"
language = "de"
backend = "omikuji"
analyzer = "snowball(german)"
vocab = "gnd-tib-core"
cluster_balanced = "False"
cluster_k = "100"
max_depth = "3"
min_df = "2"
ngram = "2"

[gnd-tib-core-xtransformer-en]
name="GND-tib-core XTransformer English"
language="en"
backend="xtransformer"
analyzer="snowball(english)"
vocab="gnd-tib-core"
batch_size=16
truncate_length=256
learning_rate=0.0001
num_train_epochs=3
max_leaf_size=1600
nr_splits=256
threshold=0.015
Cn=0.52
Cp=5.33
bootstrap_model="weighted-linear"
loss_function="weighted-squared-hinge"
max_active_matching_labels=500
negative_sampling="tfn+man"
warmup_steps=200
ensemble_method="concat-only"
post_processor="l3-hinge"
cost_sensitive_ranker=true
rel_mode="induce"
rel_norm="l1"
neg_mining_chain="tfn"
model_shortcut="FacebookAI/xlm-roberta-base"

[gnd-tib-core-xtransformer-de]
name="GND-tib-core XTransformer German"
language="de"
backend="xtransformer"
analyzer="snowball(german)"
vocab="gnd-tib-core"
batch_size=16
truncate_length=256
learning_rate=0.0001
num_train_epochs=3
max_leaf_size=1600
nr_splits=256
threshold=0.015
Cn=0.52
Cp=5.33
bootstrap_model="weighted-linear"
loss_function="weighted-squared-hinge"
max_active_matching_labels=500
negative_sampling="tfn+man"
warmup_steps=200
ensemble_method="concat-only"
post_processor="l3-hinge"
cost_sensitive_ranker=true
rel_mode="induce"
rel_norm="l1"
neg_mining_chain="tfn"
model_shortcut="FacebookAI/xlm-roberta-base"

[gnd-tib-core-bm-ensemble-en]
name = "GND-tib-core BM ensemble English"
language = "en"
backend = "ensemble"
sources = "gnd-tib-core-mllm-en:0.1271,gnd-tib-core-bonsai-en:0.8729"
vocab = "gnd-tib-core"

[gnd-tib-core-bm-ensemble-de]
name = "GND-tib-core BM ensemble German"
language = "de"
backend = "ensemble"
sources = "gnd-tib-core-mllm-de:0.1568,gnd-tib-core-bonsai-de:0.8432"
vocab = "gnd-tib-core"

[gnd-tib-core-bmx-ensemble-en]
name = "GND-tib-core BMX ensemble English"
language = "en"
backend = "ensemble"
sources = "gnd-tib-core-mllm-en:0.1671,gnd-tib-core-bonsai-en:0.6197,gnd-tib-core-xtransformer-en:0.2132"
vocab = "gnd-tib-core"

[gnd-tib-core-bmx-ensemble-de]
name = "GND-tib-core BMX ensemble German"
language = "de"
backend = "ensemble"
sources = "gnd-tib-core-mllm-de:0.1837,gnd-tib-core-bonsai-de:0.4891,gnd-tib-core-xtransformer-de:0.3272"
vocab = "gnd-tib-core"

[gnd-tib-core-nn_ensemble-en]
name = "GND-tib-core NN ensemble English"
language = "en"
backend = "nn_ensemble"
sources = "gnd-tib-core-mllm-en:0.1271,gnd-tib-core-bonsai-en:0.8729"
vocab = "gnd-tib-core"
nodes = 100
dropout_rate = 0.2
epochs = 10

[gnd-tib-core-nn_ensemble-de]
name = "GND-tib-core NN ensemble German"
language = "de"
backend = "nn_ensemble"
sources = "gnd-tib-core-mllm-de:0.1568,gnd-tib-core-bonsai-de:0.8432"
vocab = "gnd-tib-core"
nodes = 100
dropout_rate = 0.2
epochs = 10
